namespace Healthcare.Api.Service.Helper
{
    public static class BloodTestOrder
    {
        public static readonly List<string> Order = new List<string>
        {
            "Globulos Rojos",
            "Hemoglobina",
            "Hematocrito",
            "V.C.M.",
            "H.C.M.",
            "C.H.C.M.",
            "Globulos Blancos",
            "Neutrofilos cayados",
            "Neutrofilos segmentados",
            "Eosinofilos",
            "Basofilos",
            "Linfocitos",
            "Monocitos",
            "Plaquetas",
            "Eritrosedimentación 1° Hora",
            "Eritrosedimentación 2° Hora",
            "Glicemia",
            "Hemoglobina Glicosilada (HB-A1C)",
            "Uremia",
            "Creatininemia",
            "Cociente Albumina/Creatinina en Orina",
            "Uricemia",
            "Colesterol total",
            "Colesterol HDL",
            "Colesterol LDL",
            "Triglicéridos",
            "Bilirrubina directa",
            "Bilirrubina indirecta",
            "Bilirrubina total",
            "Creatinfosfoquinasa",
            "Amilasemia",
            "Nucleotidasa",
            "Glutamil Transpeptidasa",
            "Pseudocolinesterasa",
            "Transaminasa Glutamico Oxalac",
            "Transaminasa Glutamico Piruvic",
            "Fosfatasa alcalina",
            "Láctico Dehidrogenasa (LDH)",
            "Sodio",
            "Potasio",
            "Cloro plasmático",
            "Magnesio",
            "Calcemia total",
            "Vitamina D3",
            "Tirotrofina Plamatica (TSH)",
            "Tiroxina Efectiva - T4 libre",
            "Tiroxina Total (T4)",
            "Proteinas totales",
            "Albumina",
            "Ferremia",
            "Transferrina",
            "Ferritina",
            "Antigeno Prostatico Especifico",
            "Psa Libre",
            "Tiempo de coagulación",
            "Tiempo de sangria",
            "Tiempo de protrombina",
            "Tiempo de Tromboplastina (KPTT)"
        };
    }

}
