name: Deploy to Production

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t wartincodes/healthcare.api:latest . && \
          docker push wartincodes/healthcare.api:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan 52.200.237.4 >> ~/.ssh/known_hosts

      - name: Log in to Docker Hub on server
        run: |
          ssh ubuntu@52.200.237.4 "
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username wartincodes --password-stdin
          "

      - name: Pull and run Docker container on server
        run: |
          ssh ubuntu@52.200.237.4 "
          docker pull wartincodes/healthcare.api:latest && \
          CONTAINER_ID=$(docker ps -q --filter ancestor=wartincodes/healthcare.api:latest) && \
          if [ -n \"$CONTAINER_ID\" ]; then docker stop $CONTAINER_ID && docker rm $CONTAINER_ID; fi && \
          docker run -d -p 7001:80 -e ASPNETCORE_ENVIRONMENT=Development wartincodes/healthcare.api:latest
          "
